language: node_js
node_js:
  - "11.12.0"
deploy:
  provider: npm
  email: maciej@skierkowski.com
  api_key:
    secure: q4jbHu0U9/4FU2iBkvbwrvRofsQrxQ0d2UwBDhTo5iFBfgkxWQXcfw/GRV1vZIafjLUxz6wI76+5MdGcDupZKyVlPzA9WX6y8euv9zsjy2BMsKoSePJKDS0hSOEwxUWH5UmSUGabnA2j+lpK96nVXUMaFXKF7v5qn1WVzwVZ/4bgIrmSABNrxqfsiT85GaE1C6GLQVzlERdEWq2Uu/lH8u81CGkVb+2pnSJXaNUbQEQdRKy41PjQDPtbwKCPnUgLChUwwfO5YLkBDvC82tmwyUYIVuM6KsYhS1bS4OVo7xaeqkirMs1JLiaInHK922uhYAUirYkngZ/LmVEY9Uxcum491Rd6EvkaotoqQnbtZopBnjSLEorkHpjHZTJGxvu1IVDqQoNUjwjor4/FzuKdYgieLi9BG+NwSSAyN+UPdOaW5FQGJ5kayGlnIl24xCoQJnv6bM2wdi3LLbm6meN18NBHIJiV3aRuYyPiwdRjW0k4kaHK+3r4NrPXSl6WQ3CLGAwrZqepYczSKz+nqtR3xTZLPjJ4yRuMsBarLVA5AwFXABJK0TqnM7MfpWIz3Bb5cD9IXXfB+CTcnrqXlRH0C+BnJl00sVK2N2hXjijEM7WbvW1hW9BAcHTHyFIgV4E64rUCdk79PI5JaaNWTajLN0qKu/Nzg8XJMQIyXrQkJ2g=
  on:
    tags: true
    repo: safeguards-io/safeguards
after_success:
- npm run coverage